### ISSUE TITLE
Feature request set limits on humidity.

### ISSUE THREAD

**Issue by ruinpsilva** [jjpFin/DHT22-TemperatureLogger#1]
Could you add sensor limits for humidity?

Thanks

**Comment by humantorch** [comment]
As soon as my DHT22 arrives in the post I'll be working on this, when I've got it going I'll fork, add the humidity bits into this codebase and submit a PR.

**Comment by ruinpsilva** [comment]
@humantorch , Thanks.

**Comment by jjpFin** [comment]
Sorry for delayed response. 
This is on my to-do list as well, but not sure when I have time to finish it though.

**Comment by jjpFin** [comment]
First implementation for the humidity limits and email warning has been committed.
"Added possibility to configure humidity limits (high and low) to sensors. These limits work in  a same way as temperature limits. If sensor reading for humidity is outside the set limit boundaries, email warning is sent."

Example from received mail warning.
![image](https://cloud.githubusercontent.com/assets/15716797/17495416/ac2a1012-5dc1-11e6-9b4d-c3cc58c3a6a1.png)

**Comment by ruinpsilva** [comment]
@jjpFin , thanks I will test it next weekend.
