### ISSUE TITLE
Readings fail often

### ISSUE THREAD

**Issue by davidecibel** [jjpFin/DHT22-TemperatureLogger#3]
Hi,

I've set up a crontab to schedule a reading every 5 minutes. It generally works, but it fails pretty often. I've checked the logs, and the error I get is:

21-05-18 11:10:02 INFO Sensors.SensorReader Start reading values for sensor type 22 in gpio 27
21-05-18 11:10:42 ERROR Sensors.SensorReader Failed to get readings for sensor: Inside
Traceback (most recent call last):
  File "/home/pi/DHT22-TemperatureLogger/Sensors/SensorReader.py", line 58, in getSensorReadings
    temperature,humidity = self._getSensorReadings(sensorType,gpio)
  File "/home/pi/DHT22-TemperatureLogger/Sensors/SensorReader.py", line 133, in _getSensorReadings
    sensorReadings = subprocess.check_output(['sudo',self.adafruitPathConfig,sensorType,gpio])
  File "/usr/lib/python2.7/subprocess.py", line 219, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
CalledProcessError: Command '['sudo', u'/home/pi/Adafruit_Python_DHT/examples/AdafruitDHT.py', u'22', u'27']' returned non-zero exit status 1
21-05-18 11:10:42 INFO Sensors.SensorReader Sensor readings collected
21-05-18 11:10:42 INFO Sensors.SensorDataHandler Successfully read: 0 sensors. Failed to read: 1 sensor(s)
21-05-18 11:10:42 ERROR Sensors.SensorDataHandler Failed to get readings from any of the sensors. Execution terminated

Any Idea what could cause this?

**Comment by jjpFin** [comment]
Haven't seen or heard about this before and cannot say at glance what is the problem. 
Do you have multiple sensors attached to RPI and are all those failing in similar manner?
